/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AchievementCategory = "award" | "certification" | "milestone" | "promotion" | "recognition";

export type ContentType = "article" | "media_mention" | "post" | "publication" | "speaking";

export type EntityType = "event" | "institution" | "job" | "person" | "project" | "skill";

export type EventType = "conference" | "interview" | "meeting" | "networking" | "other" | "presentation" | "workshop";

export type FeedbackType = "360_feedback" | "career_coach" | "one_on_one" | "peer_feedback" | "performance_review";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type GoalStatus = "abandoned" | "completed" | "in_progress" | "not_started";

export type GoalType = "career" | "financial" | "relationship" | "skill";

export type InstitutionType = "bootcamp" | "college" | "organization" | "other" | "school" | "university";

export type InteractionType = "call" | "coffee" | "email" | "meeting";

export type LearningStatus = "abandoned" | "completed" | "in_progress" | "planned";

export type LearningType = "certification" | "conference" | "course" | "degree" | "workshop";

export type Numeric = ColumnType<string, number | string, number | string>;

export type ProjectStatus = "cancelled" | "completed" | "in_progress" | "on_hold" | "planning";

export type SkillProficiency = "advanced" | "beginner" | "expert" | "intermediate";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Achievements {
  achievedDate: Timestamp;
  category: AchievementCategory;
  createdAt: Generated<Timestamp>;
  userId: string;

  description: string;
  evidenceUrl: string | null;
  id: Generated<string>;
  quantifiableImpact: string | null;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface Compensation {
  baseSalary: Numeric;
  benefitsNote: string | null;
  bonus: Numeric | null;
  createdAt: Generated<Timestamp>;
  userId: string;

  currency: Generated<string>;
  effectiveDate: Timestamp;
  equityValue: Numeric | null;
  id: Generated<string>;
  jobId: string;
  updatedAt: Generated<Timestamp>;
}

export interface Content {
  contentType: Generated<ContentType>;
  createdAt: Generated<Timestamp>;
  userId: string;

  description: string | null;
  engagementMetrics: string | null;
  id: Generated<string>;
  platform: string | null;
  publicationDate: Timestamp;
  title: string;
  updatedAt: Generated<Timestamp>;
  url: string | null;
}

export interface Events {
  createdAt: Generated<Timestamp>;
  userId: string;

  description: string | null;
  eventDate: Timestamp | null;
  eventEndDate: Timestamp | null;
  eventType: Generated<EventType>;
  id: string;
  location: string | null;
  notes: string | null;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface Feedback {
  context: string | null;
  createdAt: Generated<Timestamp>;
  userId: string;

  feedbackDate: Timestamp;
  feedbackType: FeedbackType;
  id: Generated<string>;
  notes: string;
  personId: string;
  updatedAt: Generated<Timestamp>;
}

export interface Goals {
  createdAt: Generated<Timestamp>;
  userId: string;

  description: string;
  goalType: GoalType;
  id: Generated<string>;
  notes: string | null;
  status: Generated<GoalStatus>;
  targetDate: Timestamp;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface Institutions {
  createdAt: Generated<Timestamp>;
  userId: string;

  degree: string | null;
  endDate: Timestamp | null;
  fieldOfStudy: string | null;
  id: string;
  location: string | null;
  name: string;
  notes: string | null;
  startDate: Timestamp | null;
  type: Generated<InstitutionType>;
  updatedAt: Generated<Timestamp>;
}

export interface Interactions {
  createdAt: Generated<Timestamp>;
  userId: string;

  id: string;
  interactionDate: Timestamp;
  interactionType: InteractionType;
  notes: string | null;
  personId: string;
  projectId: string | null;
  tags: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface Jobs {
  company: string;
  createdAt: Generated<Timestamp>;
  userId: string;

  description: string | null;
  endDate: Timestamp | null;
  id: string;
  isCurrent: Generated<boolean>;
  location: string | null;
  notes: string | null;
  startDate: Timestamp | null;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface Learning {
  completionDate: Timestamp | null;
  cost: Numeric | null;
  createdAt: Generated<Timestamp>;
  userId: string;

  id: Generated<string>;
  learningType: Generated<LearningType>;
  notes: string | null;
  provider: string | null;
  skillsGained: string | null;
  startDate: Timestamp | null;
  status: Generated<LearningStatus>;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface People {
  company: string | null;
  createdAt: Generated<Timestamp>;
  userId: string;

  email: string | null;
  id: string;
  lastContactedAt: Timestamp | null;
  name: string;
  notes: string | null;
  relationshipType: Generated<string | null>;
  role: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface Projects {
  createdAt: Generated<Timestamp>;
  userId: string;

  description: string | null;
  endDate: Timestamp | null;
  id: string;
  name: string;
  startDate: Timestamp | null;
  status: Generated<ProjectStatus>;
  updatedAt: Generated<Timestamp>;
}

export interface Relationships {
  createdAt: Generated<Timestamp>;
  userId: string;

  id: string;
  notes: string | null;
  relationshipLabel: string;
  sourceId: string;
  sourceType: EntityType;
  targetId: string;
  targetType: EntityType;
  updatedAt: Generated<Timestamp>;
}

export interface Skills {
  category: string | null;
  createdAt: Generated<Timestamp>;
  userId: string;

  id: string;
  name: string;
  notes: string | null;
  proficiency: Generated<SkillProficiency>;
  updatedAt: Generated<Timestamp>;
}

export interface Users {
  createdAt: Generated<Timestamp>;
  email: string;
  id: string;
  passwordHash: string;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  users: Users;
  achievements: Achievements;
  compensation: Compensation;
  content: Content;
  events: Events;
  feedback: Feedback;
  goals: Goals;
  institutions: Institutions;
  interactions: Interactions;
  jobs: Jobs;
  learning: Learning;
  people: People;
  projects: Projects;
  relationships: Relationships;
  skills: Skills;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const ProjectStatusArrayValues: [ProjectStatus, ...ProjectStatus[]] = ["cancelled","completed","in_progress","on_hold","planning"];
export const SkillProficiencyArrayValues: [SkillProficiency, ...SkillProficiency[]] = ["advanced","beginner","expert","intermediate"];
export const InstitutionTypeArrayValues: [InstitutionType, ...InstitutionType[]] = ["bootcamp","college","organization","other","school","university"];
export const EventTypeArrayValues: [EventType, ...EventType[]] = ["conference","interview","meeting","networking","other","presentation","workshop"];
export const EntityTypeArrayValues: [EntityType, ...EntityType[]] = ["event","institution","job","person","project","skill"];
export const InteractionTypeArrayValues: [InteractionType, ...InteractionType[]] = ["call","coffee","email","meeting"];
export const FeedbackTypeArrayValues: [FeedbackType, ...FeedbackType[]] = ["360_feedback","career_coach","one_on_one","peer_feedback","performance_review"];
export const AchievementCategoryArrayValues: [AchievementCategory, ...AchievementCategory[]] = ["award","certification","milestone","promotion","recognition"];
export const GoalTypeArrayValues: [GoalType, ...GoalType[]] = ["career","financial","relationship","skill"];
export const GoalStatusArrayValues: [GoalStatus, ...GoalStatus[]] = ["abandoned","completed","in_progress","not_started"];
export const LearningTypeArrayValues: [LearningType, ...LearningType[]] = ["certification","conference","course","degree","workshop"];
export const LearningStatusArrayValues: [LearningStatus, ...LearningStatus[]] = ["abandoned","completed","in_progress","planned"];
export const ContentTypeArrayValues: [ContentType, ...ContentType[]] = ["article","media_mention","post","publication","speaking"];
// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.